const surahList = [
  { number: "1", english_name: "Al-Fatiha", arabic_name: "ٱلْفَاتِحَة" },
  { number: "2", english_name: "Al-Baqarah", arabic_name: "ٱلْبَقَرَة" },
  { number: "3", english_name: "Al Imran", arabic_name: "آلِ عِمْرَان" },
  { number: "4", english_name: "An-Nisa", arabic_name: "ٱلنِّسَاء" },
  { number: "5", english_name: "Al-Ma'idah", arabic_name: "ٱلْمَائِدَة" },
  { number: "6", english_name: "Al-An'am", arabic_name: "ٱلْأَنْعَام" },
  { number: "7", english_name: "Al-A'raf", arabic_name: "ٱلْأَعْرَاف" },
  { number: "8", english_name: "Al-Anfal", arabic_name: "ٱلْأَنْفَال" },
  { number: "9", english_name: "At-Tawbah", arabic_name: "ٱلتَّوْبَة" },
  { number: "10", english_name: "Yunus", arabic_name: "يُونُس" },
  { number: "11", english_name: "Hud", arabic_name: "هُود" },
  { number: "12", english_name: "Yusuf", arabic_name: "يُوسُف" },
  { number: "13", english_name: "Ar-Ra'd", arabic_name: "ٱلرَّعْد" },
  { number: "14", english_name: "Ibrahim", arabic_name: "إِبْرَاهِيم" },
  { number: "15", english_name: "Al-Hijr", arabic_name: "ٱلْحِجْر" },
  { number: "16", english_name: "An-Nahl", arabic_name: "ٱلنَّحْل" },
  { number: "17", english_name: "Al-Isra", arabic_name: "ٱلْإِسْرَاء" },
  { number: "18", english_name: "Al-Kahf", arabic_name: "ٱلْكَهْف" },
  { number: "19", english_name: "Maryam", arabic_name: "مَرْيَم" },
  { number: "20", english_name: "Ta-Ha", arabic_name: "طه" },
  { number: "21", english_name: "Al-Anbiya", arabic_name: "ٱلْأَنْبِيَاء" },
  { number: "22", english_name: "Al-Hajj", arabic_name: "ٱلْحَجّ" },
  { number: "23", english_name: "Al-Mu'minun", arabic_name: "ٱلْمُؤْمِنُون" },
  { number: "24", english_name: "An-Nur", arabic_name: "ٱلنُّور" },
  { number: "25", english_name: "Al-Furqan", arabic_name: "ٱلْفُرْقَان" },
  { number: "26", english_name: "Ash-Shu'ara", arabic_name: "ٱلشُّعَرَاء" },
  { number: "27", english_name: "An-Naml", arabic_name: "ٱلنَّمْل" },
  { number: "28", english_name: "Al-Qasas", arabic_name: "ٱلْقَصَص" },
  { number: "29", english_name: "Al-Ankabut", arabic_name: "ٱلْعَنْكَبُوت" },
  { number: "30", english_name: "Ar-Rum", arabic_name: "ٱلرُّوم" },
  { number: "31", english_name: "Luqmaan", arabic_name: "لُقْمَان" },
  { number: "32", english_name: "As-Sajda", arabic_name: "ٱلسَّجْدَة" },
  { number: "33", english_name: "Al-Ahzaab", arabic_name: "ٱلْأَحْزَاب" },
  { number: "34", english_name: "Saba (surah)", arabic_name: "سَبَأʾ" },
  { number: "35", english_name: "Faatir", arabic_name: "فَاطِر" },
  { number: "36", english_name: "Yaseen", arabic_name: "يس" },
  { number: "37", english_name: "As-Saaffaat", arabic_name: "ٱلصَّافَّات" },
  { number: "38", english_name: "Saad", arabic_name: "ص" },
  { number: "39", english_name: "Az-Zumar", arabic_name: "ٱلزُّمَر" },
  { number: "40", english_name: "Ghafir", arabic_name: "غَافِر" },
  { number: "41", english_name: "Fussilat", arabic_name: "فُصِّلَت" },
  { number: "42", english_name: "Ash_Shooraa", arabic_name: "ٱلشُّورىٰ" },
  { number: "43", english_name: "Az-Zukhruf", arabic_name: "ٱلْزُّخْرُف" },
  { number: "44", english_name: "Ad-Dukhaan", arabic_name: "ٱلدُّخَان" },
  { number: "45", english_name: "Al-Jaathiyah", arabic_name: "ٱلْجَاثِيَة" },
  { number: "46", english_name: "Al-Ahqaaf", arabic_name: "ٱلْأَحْقَاف" },
  { number: "47", english_name: "Muhammad", arabic_name: "مُحَمَّد" },
  { number: "48", english_name: "Al-Fath", arabic_name: "ٱلْفَتْح" },
  { number: "49", english_name: "Al-Hujuraat", arabic_name: "ٱلْحُجُرَات" },
  { number: "50", english_name: "Qaaf", arabic_name: "ق" },
  { number: "51", english_name: "Adh-Dhaariyaat", arabic_name: "ٱلذَّارِيَات" },
  { number: "52", english_name: "At-Toor", arabic_name: "ٱلطُّور" },
  { number: "53", english_name: "An-Najm", arabic_name: "ٱلنَّجْم" },
  { number: "54", english_name: "Al-Qamar", arabic_name: "ٱلْقَمَر" },
  { number: "55", english_name: "Ar-Rahman", arabic_name: "ٱلرَّحْمَٰن" },
  { number: "56", english_name: "Al-Waqi'a", arabic_name: "ٱلْوَاقِعَة" },
  { number: "57", english_name: "Al-Hadeed", arabic_name: "ٱلْحَدِيد" },
  { number: "58", english_name: "Al-Mujadila", arabic_name: "ٱلْمُجَادِلَة" },
  { number: "59", english_name: "Al-Hashr", arabic_name: "ٱلْحَشْر" },
  {
    number: "60",
    english_name: "Al-Mumtahanah",
    arabic_name: "ٱلْمُمْتَحَنَة",
  },
  { number: "61", english_name: "As-Saff", arabic_name: "ٱلصَّفّ" },
  { number: "62", english_name: "Al-Jumu'ah", arabic_name: "ٱلْجُمُعَة" },
  {
    number: "63",
    english_name: "Al-Munafiqoon",
    arabic_name: "ٱلْمُنَافِقُون",
  },
  { number: "64", english_name: "At-Taghabun", arabic_name: "ٱلتَّغَابُن" },
  { number: "65", english_name: "At-Talaq", arabic_name: "ٱلطَّلَاق" },
  { number: "66", english_name: "At-Tahreem", arabic_name: "ٱلتَّحْرِيم" },
  { number: "67", english_name: "Al-Mulk", arabic_name: "ٱلْمُلْك" },
  { number: "68", english_name: "Al-Qalam", arabic_name: "ٱلْقَلَم" },
  { number: "69", english_name: "Al-Haaqqa", arabic_name: "ٱلْحَاقَّة" },
  { number: "70", english_name: "Al-Ma'aarij", arabic_name: "ٱلْمَعَارِج" },
  { number: "71", english_name: "Nooh", arabic_name: "نُوح" },
  { number: "72", english_name: "Al-Jinn", arabic_name: "ٱلْجِنّ" },
  { number: "73", english_name: "Al-Muzzammil", arabic_name: "ٱلْمُزَّمِّل" },
  { number: "74", english_name: "Al-Muddaththir", arabic_name: "ٱلْمُدَّثِّر" },
  { number: "75", english_name: "Al-Qiyamah", arabic_name: "ٱلْقِيَامَة" },
  { number: "76", english_name: "Al-Insaan", arabic_name: "ٱلْإِنْسَان" },
  {
    number: "77",
    english_name: "Al-Mursalaat",
    arabic_name: "المرسلات ٱلْمُرْسَلَات",
  },
  { number: "78", english_name: "An-Naba'", arabic_name: "ٱلنَّبَأʾ" },
  { number: "79", english_name: "An-Naazi'aat", arabic_name: "ٱلنَّازِعَات" },
  { number: "80", english_name: "Abasa", arabic_name: "عَبَسَ" },
  { number: "81", english_name: "At-Takweer", arabic_name: "ٱلتَّكْوِير" },
  { number: "82", english_name: "Al-Infitar", arabic_name: "ٱلْإِنْفِطَار" },
  {
    number: "83",
    english_name: "Al-Mutaffifeen",
    arabic_name: "ٱلْمُطَفِّفِين",
  },
  { number: "84", english_name: "Al-Inshiqaaq", arabic_name: "ٱلْإِنْشِقَاق" },
  { number: "85", english_name: "Al-Burooj", arabic_name: "ٱلْبُرُوج" },
  { number: "86", english_name: "At-Taariq", arabic_name: "ٱلطَّارِق" },
  { number: "87", english_name: "Al-A'laa", arabic_name: "ٱلْأَعْلَىٰ" },
  { number: "88", english_name: "Al-Ghaashiyah", arabic_name: "ٱلْغَاشِيَة" },
  { number: "89", english_name: "Al-Fajr", arabic_name: "ٱلْفَجْر" },
  { number: "90", english_name: "Al-Balad", arabic_name: "ٱلْبَلَد" },
  { number: "91", english_name: "Ash-Shams", arabic_name: "ٱلشَّمْس" },
  { number: "92", english_name: "Al-Layl", arabic_name: "ٱللَّيْل" },
  { number: "93", english_name: "Ad-Dhuha", arabic_name: "ٱلضُّحَىٰ" },
  {
    number: "94",
    english_name: "Ash-Sharh (Al-Inshirah)",
    arabic_name: "ٱلشَّرْح",
  },
  { number: "95", english_name: "At-Teen", arabic_name: "ٱلتِّين" },
  { number: "96", english_name: "Al-Alaq", arabic_name: "ٱلْعَلَق" },
  { number: "97", english_name: "Al-Qadr", arabic_name: "ٱلْقَدْر" },
  { number: "98", english_name: "Al-Bayyinahh", arabic_name: "ٱلْبَيِّنَة" },
  { number: "99", english_name: "Az-Zalzalah", arabic_name: "ٱلزَّلْزَلَة" },
  { number: "100", english_name: "Al-'Aadiyaat", arabic_name: "ٱلْعَادِيَات" },
  { number: "101", english_name: "Al-Qaari'ah", arabic_name: "ٱلْقَارِعَة" },
  { number: "102", english_name: "At-Takaathur", arabic_name: "ٱلتَّكَاثُر" },
  { number: "103", english_name: "Al-'Asr", arabic_name: "ٱلْعَصْر" },
  { number: "104", english_name: "Al-Humazah", arabic_name: "ٱلْهُمَزَة" },
  { number: "105", english_name: "Al-Feel", arabic_name: "ٱلْفِيل" },
  { number: "106", english_name: "Quraysh", arabic_name: "قُرَيْش" },
  { number: "107", english_name: "Al-Maa'oon", arabic_name: "ٱلْمَاعُون" },
  { number: "108", english_name: "Al-Kawthar", arabic_name: "ٱلْكَوْثَر" },
  { number: "109", english_name: "Al-Kaafiroon", arabic_name: "ٱلْكَافِرُون" },
  { number: "110", english_name: "An-Nasr", arabic_name: "ٱلنَّصْر" },
  { number: "111", english_name: "Al-Masad", arabic_name: "ٱلْمَسَد" },
  { number: "112", english_name: "Al-Ikhlaas", arabic_name: "ٱلْإِخْلَاص" },
  { number: "113", english_name: "Al-Falaq", arabic_name: "ٱلْفَلَق" },
  { number: "114", english_name: "Al-Naas", arabic_name: "ٱلنَّاس" },
];

export default surahList;
